package com.atguigu.mybatis.dao;

import com.atguigu.mybatis.bean.ActEvtLog;
import com.atguigu.mybatis.bean.ActEvtLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActEvtLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int countByExample(ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int deleteByExample(ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int deleteByPrimaryKey(Long logNr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int insert(ActEvtLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int insertSelective(ActEvtLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    List<ActEvtLog> selectByExampleWithBLOBs(ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    List<ActEvtLog> selectByExample(ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    ActEvtLog selectByPrimaryKey(Long logNr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActEvtLog record, @Param("example") ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ActEvtLog record, @Param("example") ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int updateByExample(@Param("record") ActEvtLog record, @Param("example") ActEvtLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int updateByPrimaryKeySelective(ActEvtLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ActEvtLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbggenerated Sun Mar 31 02:52:06 CST 2019
     */
    int updateByPrimaryKey(ActEvtLog record);
}